// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9sBqkzN-rPKJCjCGXVkWbiFWXFCEr9A4',
    appId: '1:486471468703:web:316aebe489f0105dfe44aa',
    messagingSenderId: '486471468703',
    projectId: 'image-test-67470',
    authDomain: 'image-test-67470.firebaseapp.com',
    storageBucket: 'image-test-67470.appspot.com',
    measurementId: 'G-3NCHQGSD9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD28srEEtevfIZg1R2A0S1ailBGg8BlS8w',
    appId: '1:486471468703:android:4b5885cffbb933ecfe44aa',
    messagingSenderId: '486471468703',
    projectId: 'image-test-67470',
    storageBucket: 'image-test-67470.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3IkFYCHANkUcsjI2PBULCJCVpAJAE8Ks',
    appId: '1:486471468703:ios:e758e7bd3c46d5a6fe44aa',
    messagingSenderId: '486471468703',
    projectId: 'image-test-67470',
    storageBucket: 'image-test-67470.appspot.com',
    iosBundleId: 'com.example.appImageWebTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3IkFYCHANkUcsjI2PBULCJCVpAJAE8Ks',
    appId: '1:486471468703:ios:3d04ebe650678e5bfe44aa',
    messagingSenderId: '486471468703',
    projectId: 'image-test-67470',
    storageBucket: 'image-test-67470.appspot.com',
    iosBundleId: 'com.example.appImageWebTest.RunnerTests',
  );
}
