// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgPh2P7HWFxOXjKCPLHAiJgQDEeAmtA-w',
    appId: '1:860264577885:web:0f17c4e8d440c6336dc6b4',
    messagingSenderId: '860264577885',
    projectId: 'delishdelivery-16ba1',
    authDomain: 'delishdelivery-16ba1.firebaseapp.com',
    storageBucket: 'delishdelivery-16ba1.appspot.com',
    measurementId: 'G-X0TXQNDH7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGT7sSoyWjyJvyJ9-6JhB7QDygxvYIOww',
    appId: '1:860264577885:android:18eec10c772f7fe46dc6b4',
    messagingSenderId: '860264577885',
    projectId: 'delishdelivery-16ba1',
    storageBucket: 'delishdelivery-16ba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUynhIQdjObxa47D2KUmscKC023U5S3g4',
    appId: '1:860264577885:ios:f733a9a67e3a52a26dc6b4',
    messagingSenderId: '860264577885',
    projectId: 'delishdelivery-16ba1',
    storageBucket: 'delishdelivery-16ba1.appspot.com',
    iosBundleId: 'com.example.adminECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUynhIQdjObxa47D2KUmscKC023U5S3g4',
    appId: '1:860264577885:ios:0925251fb1e6ce286dc6b4',
    messagingSenderId: '860264577885',
    projectId: 'delishdelivery-16ba1',
    storageBucket: 'delishdelivery-16ba1.appspot.com',
    iosBundleId: 'com.example.adminECommerce.RunnerTests',
  );
}
